/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Dao.DBconnection;
import Dao.TaiKhoanDaoImplement;
import Model.User;
import com.sun.jdi.connect.spi.Connection;

import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.PreparedStatement;

import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import service.TaiKhoanServiceImplements;

/**
 *
 * @author phamn
 */
public class Dangkyframe extends javax.swing.JFrame {

    private static JFrame dky;
//     * Creates new form Dangkyframe
 
    public Dangkyframe() {
        initComponents();
//        btndangky.addMouseListener(new  MouseAdapter(){
//           //  DkyController ki = new DkyController(btndangky,jButton3,jtfname.getText(), jtftdn.getText(), jtfmk.getText(),jtfnlmk.getText(),jtfmail.getText(),jlmmess);
//            
//        });
//        DkyController dky = new DkyController(btndangky,jButton3,jtfname.getText(), jtftdn.getText(), jtfmk.getText(),jtfnlmk.getText(),jtfmail.getText(),jlmmess);
//      dky.setEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jlmmess = new javax.swing.JLabel();
        jlbname = new javax.swing.JLabel();
        jtfname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jlbtdn = new javax.swing.JLabel();
        jtftdn = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jlbnhaplaimk = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jlbmk = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jlbmail = new javax.swing.JLabel();
        jtfmail = new javax.swing.JTextField();
        btndangky = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jtfmk = new javax.swing.JPasswordField();
        jtfnlmk = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jlbname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbname.setText("Họ và Tên :");

        jtfname.setBorder(null);
        jtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfnameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 255));
        jLabel3.setText("Đăng ký");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jlbtdn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbtdn.setText("Tên đăng nhập :");

        jtftdn.setBorder(null);
        jtftdn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtftdnActionPerformed(evt);
            }
        });

        jlbnhaplaimk.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbnhaplaimk.setText("Nhập lại mật khẩu :");

        jlbmk.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbmk.setText("Mật khẩu :");

        jlbmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbmail.setText("Email :");

        jtfmail.setBorder(null);
        jtfmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfmailActionPerformed(evt);
            }
        });

        btndangky.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/submit.png"))); // NOI18N
        btndangky.setText("Đăng kí");
        btndangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangkyActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/undo.png"))); // NOI18N
        jButton3.setText("Quay lại");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jtfmk.setBorder(null);
        jtfmk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfmkActionPerformed(evt);
            }
        });

        jtfnlmk.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlbname, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlbtdn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlbmk, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlbmail, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlbnhaplaimk, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jtfname, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jtftdn, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jtfmail, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jtfmk)
                            .addComponent(jtfnlmk)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btndangky, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jlmmess, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbname)
                    .addComponent(jtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbtdn)
                    .addComponent(jtftdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbmk)
                    .addComponent(jtfmk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbnhaplaimk)
                    .addComponent(jtfnlmk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbmail)
                    .addComponent(jtfmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jlmmess, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btndangky, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 420, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfnameActionPerformed

    }//GEN-LAST:event_jtfnameActionPerformed

    

    private void jtftdnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtftdnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtftdnActionPerformed

    private void jtfmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfmailActionPerformed
        // TODO add your handling code here:
         jtfmail.addKeyListener(new KeyAdapter() {
    public void keyPressed(KeyEvent e) {
        if (e.getKeyCode() == KeyEvent.VK_ENTER) {
            performRegistration();
        }
    }
});

        
    }//GEN-LAST:event_jtfmailActionPerformed
  
    private void performRegistration() {
    try {
        if(jtfname.getText().isEmpty() || jtfmk.getText().isEmpty() || jtftdn.getText().isEmpty() || jtfmail.getText().isEmpty()) {
            jlmmess.setText("Xin vui lòng nhập đầy đủ thông tin!");
        } else {
            if (!isValidEmail(jtfmail.getText())) {
                jlmmess.setText("Email không hợp lệ! Phải chứa ký tự '@'.");
            } else if (!jtfmk.getText().equals(jtfnlmk.getText())) {
                jlmmess.setText("Mật khẩu nhập lại không khớp!");
            } else {
                User user = new User();
                user.setName(jtfname.getText().trim());
                user.setPass(jtfmk.getText().trim());
                user.setUser(jtftdn.getText().trim());
                user.setMail(jtfmail.getText().trim());
                user.setTinh_trang(Boolean.TRUE);
                
                TaiKhoanDaoImplement taikhoansv = new TaiKhoanDaoImplement() {};
                boolean kt = taikhoansv.isUsernameTaken(user);
                if(!kt) {
                    int ID = taikhoansv.dangky(user);
                    jlmmess.setText("Đăng kí tài khoản thành công! Xin vui lòng Đăng Nhập lại");
                } else {
                    jlmmess.setText("Tên đăng nhập đã được sử dụng! Xin vui lòng đổi tên khác");
                }
            }
        }
    } catch (Exception e) {
        jlmmess.setText("Ôi! Lỗi!!!!!");
    }
}

    private boolean isValidEmail(String email) {
        return email.contains("@");
    }

    private boolean isValidPhoneNumber(String phoneNumber) {
        return phoneNumber.matches("\\d+");
    }
    private void btndangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangkyActionPerformed
        // TODO add your handling code here:
        try {
            if(jtfname.getText().length()==0
                            ||jtfmk.getText().length()==0
                            ||jtftdn.getText().length()==0
                            ||jtfmail.getText().length()==0){
                        jlmmess.setText("Xin vui lòng nhập đầy đủ thông tin!");
                    }else {
                if (!isValidEmail(jtfmail.getText())) {
                    jlmmess.setText("Email không hợp lệ! Phải chứa ký tự '@'.");
                
                } else if (!jtfmk.getText().equals(jtfnlmk.getText())) {
                    jlmmess.setText("Mật khẩu nhập lại không khớp!");
                } else {
                            User user = new User();
                        user.setName(jtfname.getText().trim());
                        user.setPass(jtfmk.getText().trim());
                        user.setUser(jtftdn.getText().trim());
                        user.setMail(jtfmail.getText().trim());
                        user.setTinh_trang(Boolean.TRUE);
                            TaiKhoanDaoImplement taikhoansv =  new TaiKhoanDaoImplement() {};
                            boolean kt = taikhoansv.isUsernameTaken(user);
                            if(kt==false){
                            int ID = taikhoansv.dangky(user);
                            jlmmess.setText("Đăng kí tài khoản thành công! Xin vui lòng Đăng Nhập lại");
                            }else {
                                  jlmmess.setText("Tên đăng nhập đã được sử dụng! Xin vui lòng đổi tên khác");
                            }
                              
                            
                        }
                        }
                    
        } catch (Exception e) {
              jlmmess.setText("Ôi! Lỗi!!!!!");
        }
    }//GEN-LAST:event_btndangkyActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         this.dispose();
         JFrame dn = new DangNhap();
                    dn.setTitle("Đăng nhập");
                                dn.setVisible(true);
                                dn.setLocationRelativeTo(null);
                                dn.setResizable(false);
                                dn.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtfmkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfmkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfmkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dangkyframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dangkyframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dangkyframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dangkyframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            
               dky= new Dangkyframe();
               dky.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndangky;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel jlbmail;
    private javax.swing.JLabel jlbmk;
    private javax.swing.JLabel jlbname;
    private javax.swing.JLabel jlbnhaplaimk;
    private javax.swing.JLabel jlbtdn;
    private javax.swing.JLabel jlmmess;
    private javax.swing.JTextField jtfmail;
    private javax.swing.JPasswordField jtfmk;
    private javax.swing.JTextField jtfname;
    private javax.swing.JPasswordField jtfnlmk;
    private javax.swing.JTextField jtftdn;
    // End of variables declaration//GEN-END:variables
}
